title: "Matheus Mesquita Viana's Portfolio"
email: mmv5513@psu.edu
description: "Matheus Mesquita Viana \n AI Reasearch Assistant"
baseurl: "" 
url: "https://zXmattmesq.github.io" 
theme: minima
markdown: kramdown
collections:
  projects:
    output: true
