title: "Matt Viana's Portfolio"
email: "mmv5513@psu.edu"
description: "A curated space of Matt Viana's Projects, Organizations, and Work Experience"
url: "https://zXmattmesq.github.io" 
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed